Activida Tema 1 Modulo 2

1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2 matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)


In [6]:
import numpy as np

In [30]:
# crea matriz con datos
m1 = np.array([[2,12,3,5],[14,51,5,9],[6,84,44,19]])
m1

array([[ 2, 12,  3,  5],
       [14, 51,  5,  9],
       [ 6, 84, 44, 19]])

In [39]:
# crea matriz con rango
m2 = np.arange(10,22).reshape(m1.shape)
m2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [33]:
# sumar cada elemento de la matriz y alamacenar en una nueva matriz
# esto es, suma cada elemento en la misma posicion, la dimension de
# la matriz resultante es la mis de las sumadas
suma = m1 + m2
# resultado
suma

array([[ 12,  23,  15,  18],
       [ 28,  66,  21,  26],
       [ 24, 103,  64,  40]])

2. Cree una matriz de identidad de dimensión 4.


In [11]:
mi = np.identity(4)
mi

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una
matriz numpy booleana.


In [40]:
mbinaria = np.full((7, 3), [0, 1, 0])
mbinaria

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [41]:
mbinaria = np.full_like(mbinaria,mbinaria,dtype=bool)
mbinaria

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

4. Genere una secuencia de números en forma de matriz numpy de 0 a
100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...

In [28]:
secuencia = np.arange(0,100,2)
secuencia

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])